INSERT INTO PATIENT(ID,PATIENT_ID,BIRTH_DATE,GIVEN_NAME,FAMILY_NAME,ADDITIONAL_NAME,GENDER,EMAIL,HEIGHT,WEIGHT)
  (SELECT * FROM CSVREAD('classpath:patients-uuid-char.csv'));
INSERT INTO MEDICATION(ID,RX_NORM_CODE,GENERIC_NAME,TRADE_NAME,VALUE,UNIT)
  (SELECT * FROM CSVREAD('classpath:medications.csv'));